# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
nom = "7.1.3"
rayon = "1.8"

[workspace.lints.rust]
unused = "allow"